# Generated by Django 4.0.5 on 2022-06-27 03:48

from django.db import migrations, models
import django.db.models.deletion
import log.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertedDevices',
            fields=[
                ('device_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('MAC', models.CharField(blank=True, max_length=17)),
                ('POS', models.CharField(blank=True, max_length=17)),
                ('PRINTER', models.CharField(blank=True, max_length=17)),
                ('CUTTER', models.CharField(blank=True, max_length=17)),
                ('API', models.IntegerField()),
                ('NUMBER', models.IntegerField(blank=True)),
                ('DateTime', models.DateTimeField(auto_now=True)),
                ('lastUpdate', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('device_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('MAC', models.CharField(blank=True, max_length=17)),
                ('POS', models.IntegerField()),
                ('PRINTER', models.IntegerField()),
                ('CUTTER', models.IntegerField()),
                ('API', models.IntegerField()),
                ('NUMBER', models.IntegerField(blank=True)),
                ('DateTime', models.DateTimeField(auto_now=True)),
                ('lastUpdate', models.DateTimeField(blank=True, null=True)),
                ('UpdateVersion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceTransaction',
            fields=[
                ('device_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('MAC', models.CharField(blank=True, max_length=17)),
                ('POS', models.CharField(blank=True, max_length=17)),
                ('PRINTER', models.CharField(blank=True, max_length=17)),
                ('CUTTER', models.CharField(blank=True, max_length=17)),
                ('API', models.IntegerField()),
                ('NUMBER', models.IntegerField(blank=True)),
                ('PAYMENT', models.JSONField()),
                ('DATETIME', models.DateTimeField(auto_now=True)),
                ('lastUpdate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=log.models.upload_to)),
                ('filename', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DevicePayment',
            fields=[
                ('CODE', models.IntegerField(blank=True)),
                ('REF', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('PRICE', models.IntegerField(blank=True)),
                ('DATETIME', models.CharField(blank=True, max_length=20)),
                ('device_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.devices')),
            ],
        ),
    ]
