# Generated by Django 4.0.5 on 2022-07-04 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='converteddevices',
            name='DateTime',
        ),
        migrations.RemoveField(
            model_name='converteddevices',
            name='lastUpdate',
        ),
    ]
