# Generated by Django 4.0.5 on 2022-07-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_remove_converteddevices_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='converteddevices',
            name='DateTime',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AddField(
            model_name='converteddevices',
            name='lastUpdate',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
